/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AuctionState = IDL.Record({
  'current_player_id' : IDL.Opt(IDL.Nat),
  'current_bid' : IDL.Nat,
  'leading_team_id' : IDL.Opt(IDL.Nat),
  'is_active' : IDL.Bool,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'image_url' : IDL.Text,
  'name' : IDL.Text,
  'base_price' : IDL.Nat,
  'sold_to' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'sold_price' : IDL.Opt(IDL.Nat),
});
export const Dashboard = IDL.Record({
  'total_spent' : IDL.Nat,
  'remaining_players' : IDL.Nat,
  'most_expensive_player' : IDL.Opt(Player),
  'sold_players' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'purse_total' : IDL.Nat,
  'icon_player_name' : IDL.Text,
  'purse_remaining' : IDL.Nat,
  'players_bought' : IDL.Nat,
  'owner_name' : IDL.Text,
  'is_locked' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addPlayer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [Result],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [Result], []),
  'editTeamPurse' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
  'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
  'getDashboard' : IDL.Func([], [Dashboard], ['query']),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getResults' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Player, IDL.Opt(Team)))],
      ['query'],
    ),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'placeBid' : IDL.Func([IDL.Nat], [Result], []),
  'resetAuction' : IDL.Func([], [], []),
  'selectPlayer' : IDL.Func([IDL.Nat], [Result], []),
  'sellPlayer' : IDL.Func([], [Result], []),
  'updatePlayer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [Result],
      [],
    ),
  'updateTeam' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AuctionState = IDL.Record({
    'current_player_id' : IDL.Opt(IDL.Nat),
    'current_bid' : IDL.Nat,
    'leading_team_id' : IDL.Opt(IDL.Nat),
    'is_active' : IDL.Bool,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'image_url' : IDL.Text,
    'name' : IDL.Text,
    'base_price' : IDL.Nat,
    'sold_to' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'sold_price' : IDL.Opt(IDL.Nat),
  });
  const Dashboard = IDL.Record({
    'total_spent' : IDL.Nat,
    'remaining_players' : IDL.Nat,
    'most_expensive_player' : IDL.Opt(Player),
    'sold_players' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'purse_total' : IDL.Nat,
    'icon_player_name' : IDL.Text,
    'purse_remaining' : IDL.Nat,
    'players_bought' : IDL.Nat,
    'owner_name' : IDL.Text,
    'is_locked' : IDL.Bool,
  });
  
  return IDL.Service({
    'addPlayer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [Result],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [Result], []),
    'editTeamPurse' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
    'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
    'getDashboard' : IDL.Func([], [Dashboard], ['query']),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getResults' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Player, IDL.Opt(Team)))],
        ['query'],
      ),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'placeBid' : IDL.Func([IDL.Nat], [Result], []),
    'resetAuction' : IDL.Func([], [], []),
    'selectPlayer' : IDL.Func([IDL.Nat], [Result], []),
    'sellPlayer' : IDL.Func([], [Result], []),
    'updatePlayer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [Result],
        [],
      ),
    'updateTeam' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };