/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amount = bigint;
export interface AuctionState {
  'currentPlayerId' : [] | [PlayerId],
  'leadingTeamId' : [] | [TeamId],
  'isActive' : boolean,
  'currentBid' : Amount,
}
export type Category = { 'bowler' : null } |
  { 'allrounder' : null } |
  { 'batsman' : null };
export interface Dashboard {
  'remainingPlayers' : bigint,
  'unsoldPlayers' : bigint,
  'totalSpent' : Amount,
  'mostExpensivePlayer' : [] | [Player],
  'soldPlayers' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Player {
  'id' : PlayerId,
  'status' : Status,
  'soldTo' : [] | [TeamId],
  'name' : string,
  'soldPrice' : [] | [Amount],
  'imageUrl' : string,
  'category' : Category,
  'rating' : Rating,
  'basePrice' : Amount,
}
export type PlayerId = bigint;
export interface PlayerWithTeam { 'player' : Player, 'team' : [] | [Team] }
export type Rating = bigint;
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Status = { 'upcoming' : null } |
  { 'live' : null } |
  { 'sold' : null } |
  { 'unsold' : null };
export interface Team {
  'id' : TeamId,
  'purseAmountLeft' : Amount,
  'teamIconPlayer' : string,
  'teamLogo' : TeamLogo,
  'isTeamLocked' : boolean,
  'ownerName' : string,
  'name' : string,
  'purseAmountTotal' : Amount,
  'numberOfPlayers' : bigint,
}
export type TeamId = bigint;
export type TeamLogo = [] | [ExternalBlob];
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPlayer' : ActorMethod<[string, Category, Amount, string, Rating], Result>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deletePlayer' : ActorMethod<[PlayerId], Result>,
  'editTeamPurse' : ActorMethod<[TeamId, Amount], Result>,
  'getAuctionState' : ActorMethod<[], AuctionState>,
  'getDashboard' : ActorMethod<[], Dashboard>,
  'getPlayerById' : ActorMethod<[PlayerId], [] | [Player]>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getPlayersByCategory' : ActorMethod<[Category], Array<Player>>,
  'getRemainingPurse' : ActorMethod<[TeamId], [] | [Amount]>,
  'getResults' : ActorMethod<[], Array<PlayerWithTeam>>,
  'getSettings' : ActorMethod<[], string>,
  'getTeamById' : ActorMethod<[TeamId], [] | [Team]>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'initialize' : ActorMethod<[], boolean>,
  'markPlayerUnsold' : ActorMethod<[], Result>,
  'placeBid' : ActorMethod<[TeamId], Result>,
  'putPlayerBackToAuction' : ActorMethod<[PlayerId], Result>,
  'resetAuction' : ActorMethod<[], undefined>,
  'saveSettings' : ActorMethod<[string], undefined>,
  'selectPlayer' : ActorMethod<[PlayerId], Result>,
  'sellPlayer' : ActorMethod<[], Result>,
  'unsellPlayer' : ActorMethod<[PlayerId], Result>,
  'updatePlayer' : ActorMethod<
    [PlayerId, string, Category, Amount, string, Rating],
    Result
  >,
  'updateTeam' : ActorMethod<[TeamId, string, string, string], Result>,
  'uploadTeamLogo' : ActorMethod<[TeamId, ExternalBlob], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];