/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionState {
  'current_player_id' : [] | [bigint],
  'current_bid' : bigint,
  'leading_team_id' : [] | [bigint],
  'is_active' : boolean,
}
export interface Dashboard {
  'total_spent' : bigint,
  'remaining_players' : bigint,
  'most_expensive_player' : [] | [Player],
  'sold_players' : bigint,
}
export interface Player {
  'id' : bigint,
  'status' : string,
  'image_url' : string,
  'name' : string,
  'base_price' : bigint,
  'sold_to' : [] | [bigint],
  'category' : string,
  'rating' : bigint,
  'sold_price' : [] | [bigint],
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Team {
  'id' : bigint,
  'name' : string,
  'purse_total' : bigint,
  'icon_player_name' : string,
  'purse_remaining' : bigint,
  'players_bought' : bigint,
  'owner_name' : string,
  'is_locked' : boolean,
}
export interface _SERVICE {
  'addPlayer' : ActorMethod<[string, string, bigint, string, bigint], Result>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deletePlayer' : ActorMethod<[bigint], Result>,
  'editTeamPurse' : ActorMethod<[bigint, bigint], Result>,
  'getAuctionState' : ActorMethod<[], AuctionState>,
  'getDashboard' : ActorMethod<[], Dashboard>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getResults' : ActorMethod<[], Array<[Player, [] | [Team]]>>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'placeBid' : ActorMethod<[bigint], Result>,
  'resetAuction' : ActorMethod<[], undefined>,
  'selectPlayer' : ActorMethod<[bigint], Result>,
  'sellPlayer' : ActorMethod<[], Result>,
  'updatePlayer' : ActorMethod<
    [bigint, string, string, bigint, string, bigint],
    Result
  >,
  'updateTeam' : ActorMethod<[bigint, string, string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];