/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    status: string;
    image_url: string;
    name: string;
    base_price: bigint;
    sold_to?: bigint;
    category: string;
    rating: bigint;
    sold_price?: bigint;
}
export interface Dashboard {
    total_spent: bigint;
    remaining_players: bigint;
    most_expensive_player?: Player;
    sold_players: bigint;
}
export interface AuctionState {
    current_player_id?: bigint;
    current_bid: bigint;
    leading_team_id?: bigint;
    is_active: boolean;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Team {
    id: bigint;
    name: string;
    purse_total: bigint;
    icon_player_name: string;
    purse_remaining: bigint;
    players_bought: bigint;
    owner_name: string;
    is_locked: boolean;
}
export interface backendInterface {
    addPlayer(name: string, category: string, basePrice: bigint, imageUrl: string, rating: bigint): Promise<Result>;
    adminLogin(password: string): Promise<boolean>;
    deletePlayer(playerId: bigint): Promise<Result>;
    editTeamPurse(teamId: bigint, newPurse: bigint): Promise<Result>;
    getAuctionState(): Promise<AuctionState>;
    getDashboard(): Promise<Dashboard>;
    getPlayers(): Promise<Array<Player>>;
    getResults(): Promise<Array<[Player, Team | null]>>;
    getTeams(): Promise<Array<Team>>;
    placeBid(teamId: bigint): Promise<Result>;
    resetAuction(): Promise<void>;
    selectPlayer(playerId: bigint): Promise<Result>;
    sellPlayer(): Promise<Result>;
    updatePlayer(playerId: bigint, name: string, category: string, basePrice: bigint, imageUrl: string, rating: bigint): Promise<Result>;
    updateTeam(teamId: bigint, name: string, ownerName: string, iconPlayerName: string): Promise<Result>;
}
import type { AuctionState as _AuctionState, Dashboard as _Dashboard, Player as _Player, Result as _Result, Team as _Team } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPlayer(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async deletePlayer(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async editTeamPurse(arg0: bigint, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.editTeamPurse(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTeamPurse(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuctionState(): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuctionState();
                return from_candid_AuctionState_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuctionState();
            return from_candid_AuctionState_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_Dashboard_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_Dashboard_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResults(): Promise<Array<[Player, Team | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return result;
        }
    }
    async placeBid(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAuction(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAuction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAuction();
            return result;
        }
    }
    async selectPlayer(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.selectPlayer(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectPlayer(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sellPlayer(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sellPlayer();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sellPlayer();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlayer(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeam(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuctionState_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionState): AuctionState {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    image_url: string;
    name: string;
    base_price: bigint;
    sold_to: [] | [bigint];
    category: string;
    rating: bigint;
    sold_price: [] | [bigint];
}): {
    id: bigint;
    status: string;
    image_url: string;
    name: string;
    base_price: bigint;
    sold_to?: bigint;
    category: string;
    rating: bigint;
    sold_price?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        image_url: value.image_url,
        name: value.name,
        base_price: value.base_price,
        sold_to: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sold_to)),
        category: value.category,
        rating: value.rating,
        sold_price: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sold_price))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    current_player_id: [] | [bigint];
    current_bid: bigint;
    leading_team_id: [] | [bigint];
    is_active: boolean;
}): {
    current_player_id?: bigint;
    current_bid: bigint;
    leading_team_id?: bigint;
    is_active: boolean;
} {
    return {
        current_player_id: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.current_player_id)),
        current_bid: value.current_bid,
        leading_team_id: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.leading_team_id)),
        is_active: value.is_active
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total_spent: bigint;
    remaining_players: bigint;
    most_expensive_player: [] | [_Player];
    sold_players: bigint;
}): {
    total_spent: bigint;
    remaining_players: bigint;
    most_expensive_player?: Player;
    sold_players: bigint;
} {
    return {
        total_spent: value.total_spent,
        remaining_players: value.remaining_players,
        most_expensive_player: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.most_expensive_player)),
        sold_players: value.sold_players
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Player, [] | [_Team]]): [Player, Team | null] {
    return [
        from_candid_Player_n9(_uploadFile, _downloadFile, value[0]),
        from_candid_opt_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Player, [] | [_Team]]>): Array<[Player, Team | null]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
